name: Build

on:
  push:
  pull_request:
  release:
    types:
      - created

jobs:

  build_mac_toolchain:
    name: Mac Toolchain
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Toolchain
        run: |
           chmod 755 mac-toolchain-build
           BUILD_VERSION="$(./mac-toolchain-build --version | cut -d ' ' -f 2)"
           BUILD_VERSION="${BUILD_VERSION:-0.0.0}"
           ./mac-toolchain-build mac-toolchain-"${BUILD_VERSION}"
           tar -cvzf mac-toolchain-"${BUILD_VERSION}".tar.gz mac-toolchain-"${BUILD_VERSION}"/
      - name: Upload Release Asset
        if: github.event_name == 'release'
        uses: AButler/upload-release-assets@v2.0
        with:
          files: '*.tar.gz'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
